name: Push templates to S3
run-name: ${{ github.workflow }}
on: [push, workflow_dispatch]
jobs:
  upload-to-s3:
    runs-on: ubuntu-latest
    steps:
      - name: "Update cache"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
          AWS_DEFAULT_REGION: ap-south-1
        run: |
          export DEBIAN_FRONTEND=noninteractive
          ls
          aws sts get-caller-identity
          aws s3 cp --include "*-template.yml" --exclude ".git*" . s3://turn-one-iaac/ --recursive
          aws s3 ls s3://turn-one-iaac
          aws --version
