name: Push templates to S3
run-name: ${{ github.workflow }}
on: [push]
jobs:
  Install-AWS-CLI:
    runs-on: ubuntu-latest
    steps:
      - name: "Update cache"
        run: sudo apt-get update -y && sudo apt-get upgrade -y --no-install-recommends
      - name: "Install AWS CLI"
        run: |
          sudo apt install -y --no-install-recommends curl wget && \
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" && \
          unzip awscliv2.zip && \
          sudo ./aws/install
      - name: "Configure AWS CLI"
        run: |
          export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY }}
          export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
          export AWS_ACCOUNT_ID=${{ secrets.AWS_ACCOUNT_ID }}
          export AWS_DEFAULT_REGION=ap-south-1
      - name: Check the AWS account
        run: aws sts get-caller-identity