name: Push templates to S3
run-name: ${{ github.workflow }}
on: [push]
jobs:
  configure-aws-cli:
    runs-on: ubuntu-latest
    steps:
      - name: "Update cache"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
          AWS_DEFAULT_REGION: ap-south-1
        run: |
          export DEBIAN_FRONTEND=noninteractive
          env
          sudo apt-get update -y && sudo apt-get upgrade -y
          snap version
          sudo snap install aws-cli --classic
          aws --version
          aws sts get-caller-identity